export const DocumentPhotoEnum = {
    DRIVER_LICENSE: 'DRIVER_LICENSE',
    VEHICLE_REGISTRATION: 'VEHICLE_REGISTRATION',
    INSURANCE_CERTIFICATE: 'INSURANCE_CERTIFICATE',
    NATIONAL_ID: 'NATIONAL_ID',
    PROFILE_PHOTO: 'PROFILE_PHOTO',
    VEHICLE_PHOTO: 'VEHICLE_PHOTO',
    INSPECTION_REPORT: 'INSPECTION_REPORT',
    OTHER: 'OTHER',
};
